module serpent:
    snakefile: "/home/jb/development/serpent/workflow/Snakefile"

OUTDIR = config["outdir"]["act"]["relatedness_ancestry"]

rule all:
    input: 
        pcr=f"{OUTDIR}/results/2_relatedness_ancestry/pcr_b.rds",
        grm=f"{OUTDIR}/results/2_relatedness_ancestry/pcr_grm_b.rds",

GDS_OUTDIR = config["outdir"]["act"]["convert_gt_gds"]
QC_OUTDIR = config["outdir"]["act"]["sample_variant_qc"]

GENESIS_IMG = config["images"]["genesis"]

# Upstream inter-module inputs
GDS = f"{GDS_OUTDIR}/results/act_genotyped.gds"
SAMPLES_PASS_QC = f"{QC_OUTDIR}/results/samples_pass_qc.rds"
SAMPLE_METRICS = f"{QC_OUTDIR}/results/sample_metrics.rds"
VARIANTS_PASS_QC = f"{QC_OUTDIR}/results/variants_pass_qc.rds"

use rule snpgdsIBDKING from serpent as serpent_snpgdsIBDKING with:
    container: GENESIS_IMG
    input:
        gds_fn=GDS,
        sample_id=SAMPLES_PASS_QC,
        snp_id=VARIANTS_PASS_QC,
    output:
        king=f"{OUTDIR}/results/king.rds",
        grm=f"{OUTDIR}/results/king_grm.rds",
    log: f"{OUTDIR}/logs/snpgdsIBDKING.log"
    params:
        missing_rate=None,
        type="KING-robust",
        verbose=True,

use rule get_var_data from serpent as serpent_get_var_data with:
    container: GENESIS_IMG
    input:
        gds_fn=GDS,
        variant_id=VARIANTS_PASS_QC,
    output:
        f"{OUTDIR}/results/snps_to_prune.rds",
    log: f"{OUTDIR}/logs/get_var_data.log"
    params:
        build="hg38",

use rule snpgdsLDpruning from serpent as serpent_ld_prune with:
    container: GENESIS_IMG
    input:
        gds_fn=GDS,
        sample_id=SAMPLES_PASS_QC,
        variant_id=f"{OUTDIR}/results/snps_to_prune.rds",
    output:
        f"{OUTDIR}/results/snps_pruned.rds",
    log: f"{OUTDIR}/logs/snpgdsLDpruning.log"
    params:
        method="corr",
        ld_threshold=0.2,
        maf=0.01,
        seed=51,

use rule pcair from serpent as serpent_pcair_a with:
    container: GENESIS_IMG
    input:
        gds_fn=GDS,
        kinobj=f"{OUTDIR}/results/king_grm.rds",
        divobj=f"{OUTDIR}/results/king_grm.rds",
        sample_include=SAMPLES_PASS_QC,
        snp_include=f"{OUTDIR}/results/snps_pruned.rds",
        pheno=SAMPLE_METRICS,
    output:
        pcair=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_a.rds",
        pcs=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_a_pcs.rds",
        unrels=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_a_unrels.rds",
        rels=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_a_rels.rds",
        scree=f"{OUTDIR}/figures/pcair_a/scree.png",
    log: f"{OUTDIR}/logs/pcair_a.log"
    params:
        div_thresh=-2**(-11/2),
        kin_thresh=2**(-11/2),
        n_pairs=4,
        maf=0.05,
        eigen_cnt=8,
        pc_pairs_group="cohort",
        pairs_prfx=f"{OUTDIR}/figures/pcair_a/pc_pairs",
        id_name="id",
    threads: 30

use rule pcrelate from serpent as serpent_pcrelate_a with:
    container: GENESIS_IMG
    input:
        gds_fn=GDS,
        sample_include=SAMPLES_PASS_QC,
        variant_id=f"{OUTDIR}/results/snps_pruned.rds",
        pca=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_a.rds",
    output:
        pcr=f"{OUTDIR}/results/2_relatedness_ancestry/pcr_a.rds",
        grm=f"{OUTDIR}/results/2_relatedness_ancestry/pcr_grm_a.rds",
    log: f"{OUTDIR}/logs/pcrelate_a.log"
    params:
        n_pcs=3,
        maf_thresh=0.05,
        small_samp_correct=True,
        variantBlock=3000,
        verbose=True,
        scaleKin=1,
    threads: 30

use rule pcair from serpent as serpent_pcair_b with:
    container: GENESIS_IMG
    input:
        gds_fn=GDS,
        kinobj=f"{OUTDIR}/results/2_relatedness_ancestry/pcr_grm_a.rds",
        divobj=f"{OUTDIR}/results/king_grm.rds",
        sample_include=SAMPLES_PASS_QC,
        snp_include=f"{OUTDIR}/results/snps_pruned.rds",
        pheno=SAMPLE_METRICS,
    output:
        pcair=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_b.rds",
        pcs=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_b_pcs.rds",
        unrels=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_b_unrels.rds",
        rels=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_b_rels.rds",
        scree=f"{OUTDIR}/figures/pcair_b/scree.png",
    log: f"{OUTDIR}/logs/pcair_b.log"
    params:
        div_thresh=-2**(-11/2),
        kin_thresh=2**(-11/2),
        n_pairs=4,
        maf=0.05,
        eigen_cnt=8,
        pc_pairs_group="cohort",
        pairs_prfx=f"{OUTDIR}/figures/pcair_b/pc_pairs",
        id_name="id",
    threads: 30

use rule pcrelate from serpent as serpent_pcrelate_b with:
    container: GENESIS_IMG
    input:
        gds_fn=GDS,
        sample_include=SAMPLES_PASS_QC,
        variant_id=f"{OUTDIR}/results/snps_pruned.rds",
        pca=f"{OUTDIR}/results/2_relatedness_ancestry/pcair_b.rds",
    output:
        pcr=f"{OUTDIR}/results/2_relatedness_ancestry/pcr_b.rds",
        grm=f"{OUTDIR}/results/2_relatedness_ancestry/pcr_grm_b.rds",
    log: f"{OUTDIR}/logs/pcrelate_b.log"
    params:
        n_pcs=3,
        maf_thresh=0.05,
        small_samp_correct=True,
        variantBlock=3000,
        verbose=True,
        scaleKin=2,
    threads: 30
